module VerifyExamples.AssocList.Eq0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import AssocList exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#eq: \n\n    eq\n        (fromList [ ( \"a\", 1 ), ( \"b\", 2 ) ])\n        (fromList [ ( \"b\", 2 ), ( \"a\", 1 ) ])\n    --> True" <|
        \() ->
            Expect.equal
                (
                eq
                    (fromList [ ( "a", 1 ), ( "b", 2 ) ])
                    (fromList [ ( "b", 2 ), ( "a", 1 ) ])
                )
                (
                True
                )