module VerifyExamples.AssocList.Foldl0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import AssocList exposing (..)



users : Dict String Int
users =
    empty
        |> insert "Alice" 28
        |> insert "Bob" 19
        |> insert "Chuck" 33



spec0 : Test.Test
spec0 =
    Test.test "#foldl: \n\n    foldl (\\name age result -> age :: result) [] users\n    --> [28,19,33]" <|
        \() ->
            Expect.equal
                (
                foldl (\name age result -> age :: result) [] users
                )
                (
                [28,19,33]
                )