module VerifyExamples.AssocList.FromList0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import AssocList exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#fromList: \n\n    toList (fromList [ ( \"Alice\", 1 ), ( \"Bob\", 2 ), ( \"Alice\", 3 ) ])\n    --> [ ( \"Alice\", 1 ), ( \"Bob\", 2 ) ]" <|
        \() ->
            Expect.equal
                (
                toList (fromList [ ( "Alice", 1 ), ( "Bob", 2 ), ( "Alice", 3 ) ])
                )
                (
                [ ( "Alice", 1 ), ( "Bob", 2 ) ]
                )