module VerifyExamples.AssocList.Get0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import AssocList exposing (..)

type Animal
    = Cat
    | Mouse

animals : Dict String Animal
animals = fromList [ ("Tom", Cat), ("Jerry", Mouse) ]



spec0 : Test.Test
spec0 =
    Test.test "#get: \n\n    get \"Spike\" animals\n    --> Nothing" <|
        \() ->
            Expect.equal
                (
                get "Spike" animals
                )
                (
                Nothing
                )