module VerifyExamples.AssocList.Get1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import AssocList exposing (..)

type Animal
    = Cat
    | Mouse

animals : Dict String Animal
animals = fromList [ ("Tom", Cat), ("Jerry", Mouse) ]



spec1 : Test.Test
spec1 =
    Test.test "#get: \n\n    get \"Jerry\" animals\n    --> Just Mouse" <|
        \() ->
            Expect.equal
                (
                get "Jerry" animals
                )
                (
                Just Mouse
                )