module VerifyExamples.AssocList.Get2 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import AssocList exposing (..)

type Animal
    = Cat
    | Mouse

animals : Dict String Animal
animals = fromList [ ("Tom", Cat), ("Jerry", Mouse) ]



spec2 : Test.Test
spec2 =
    Test.test "#get: \n\n    get \"Tom\" animals\n    --> Just Cat" <|
        \() ->
            Expect.equal
                (
                get "Tom" animals
                )
                (
                Just Cat
                )