module VerifyExamples.AssocList.IsEmpty0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import AssocList exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#isEmpty: \n\n    isEmpty empty\n    --> True" <|
        \() ->
            Expect.equal
                (
                isEmpty empty
                )
                (
                True
                )