module VerifyExamples.AssocList.Size0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import AssocList exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#size: \n\n    size (insert 1 \"b\" (singleton 1 \"a\"))\n    --> 1" <|
        \() ->
            Expect.equal
                (
                size (insert 1 "b" (singleton 1 "a"))
                )
                (
                1
                )