module VerifyExamples.AssocList.Size1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import AssocList exposing (..)







spec1 : Test.Test
spec1 =
    Test.test "#size: \n\n    size (fromList [ ( \"a\", 1 ), ( \"b\", 2 ), ( \"c\", 3 ) ])\n    --> 3" <|
        \() ->
            Expect.equal
                (
                size (fromList [ ( "a", 1 ), ( "b", 2 ), ( "c", 3 ) ])
                )
                (
                3
                )