module VerifyExamples.MARKDOWN.README.Test0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import AssocList as Dict exposing (Dict)

type Movie
    = LittleMermaid
    | LionKing
    | ToyStory
type Character
    = Ariel
    | Simba
    | Mufasa
    | Woody

characterToMovie : Dict Character Movie
characterToMovie =
    Dict.fromList
        [ ( Ariel, LittleMermaid )
        , ( Simba, LionKing )
        , ( Mufasa, LionKing )
        , ( Woody, ToyStory )
        ]



spec0 : Test.Test
spec0 =
    Test.test "Documentation VerifyExamples: \n\n    Dict.get Simba characterToMovie\n    --> Just LionKing" <|
        \() ->
            Expect.equal
                (
                Dict.get Simba characterToMovie
                )
                (
                Just LionKing
                )