module VerifyExamples.UniqueList.Filter0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import UniqueList exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#filter: \n\n    positives =\n        filter (\\x -> x > 0) (fromList [ -2, -1, 0, 1, 2 ])\n    --> positives == fromList [ 0, 1, 2 ]" <|
        \() ->
            Expect.equal
                (
                positives =
                    filter (\x -> x > 0) (fromList [ -2, -1, 0, 1, 2 ])
                )
                (
                positives == fromList [ 0, 1, 2 ]
                )