module VerifyExamples.UniqueList.Union0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import UniqueList exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#union: \n\n    toList (union (fromList [ \"Bob\" ]) (fromList [ \"Alice\", \"Bob\" ]))\n    --> [ \"Bob\", \"Alice\" ]" <|
        \() ->
            Expect.equal
                (
                toList (union (fromList [ "Bob" ]) (fromList [ "Alice", "Bob" ]))
                )
                (
                [ "Bob", "Alice" ]
                )